sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.26.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d --build

script:
  - docker ps
  - docker exec -it property_backend_1 ls
  - docker exec -it balihot-property_backend_1 pip install coveralls
  - docker exec -it balihot-property_backend_1 flask db init
  - docker exec -it balihot-property_backend_1 flask migrate -m "init db"
  - docker exec -it balihot-property_backend_1 flask upgrade
  - docker exec -it balihot-property_backend_1 touch services/tests/system/__init__.py

after_script:
  - docker-compose down
